### ISSUE TITLE
find a way for showing images

### ISSUE THREAD

**Issue by sinadarvi** [KotlinFarsi/KotlinFarsi-WebSite#6]
i tested some of the images in the markdown sourced from assets folder, and when i run the `ng serve` the images will not showup and files cant be shown! i should find a way to do that

**Comment by sinadarvi** [comment]
i think the final steps would be that i link the images from github source, the way i did for syncmusic

**Comment by HajSnoop** [comment]
this issue is being closed due to changes in the base of Kotlin-website considering Jekyll.
